
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 30 20:53:38 CST 2022
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Variable = 2;
  public static final int Decimal = 9;
  public static final int Multiplicacion = 6;
  public static final int Division = 7;
  public static final int ERROR = 10;
  public static final int EOF = 0;
  public static final int Entero = 8;
  public static final int Suma = 4;
  public static final int error = 1;
  public static final int Igual = 3;
  public static final int Resta = 5;
}

